algoritmo "Trabalhando com Tipos"

var
  palavra1, palavra2, palavra3: literal
  numero1, numero2, numero3: inteiro
inicio
  Escreval("Palavra 1 :")
  leia(palavra1)
  Escreval("Palavra 2 :")
  leia(palavra2)
  Escreval("Número 1 :")
  leia(numero1)
  Escreval("Número 2 :")
  leia(numero2)
  palavra3 <- palavra1 + " " + palavra2
  numero3 <- numero1 + numero2
  Escreval(palavra3)
  Escreval(numero3)
fimalgoritmo
